# -*- coding: utf-8 -*-
"""telecustomer-churn-analysis-ibm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwP9ylvFFvy6t-1ZKRgH2a0OgcAUmUY3
"""

from google.colab import files
uploaded = files.upload()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Assuming 'IBM (3).csv' is the file you uploaded and want to use
file_name = list(uploaded.keys())[0]
IBM = pd.read_csv(file_name)
print(IBM.head())
print(IBM.describe())
print(IBM.shape)

male_customer = IBM[IBM['Gender']=='Male']
female_customer=IBM[IBM['Gender']=='Female']
print(male_customer.head(4))
print(female_customer.head(4))

dissatisfied_churn = IBM[(IBM['Churn Category'].str.contains('Dissatisfaction', case=False, na=False))]

# Step 5: Get the total count of such customers
total_dissatisfied_churn = dissatisfied_churn.shape[0]

print("Total number of customers who churned due to dissatisfaction:", total_dissatisfied_churn)

citywise_counts = dissatisfied_churn.groupby('City')['CUSTOMER_id'].count().reset_index()

# Step 4: Sort (optional, for clean display)
citywise_counts = citywise_counts.sort_values(by='CUSTOMER_id', ascending=False).head(10)

# Step 5: Create a pie chart
plt.figure(figsize=(8, 8))
plt.pie(
    citywise_counts['CUSTOMER_id'],
    labels=citywise_counts['City'],
    autopct='%1.1f%%',
    startangle=90
)
plt.title('top 10 citywise Churn due to Dissatisfaction ')
plt.show()